spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 940193236635-fdj6gk65pc0d1o1g9m6d8j35h4hfvv2b.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          kakao:
            client-id: c253dd02cc022584a8011b23654e1d22
            client-secret: k4YywS2eh3ayB9c7nyABAFJyDfoxebDz
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao
          naver:
            client-id: QaTFM0cRXeiFHtG7qkpY
            client-secret: Hyr2kvz8jn
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response