spring:
  devtools:
    livereload:
      enabled: true
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  profiles:
    include: oauth
  session:
    store-type: jdbc